[tool.ruff]
line-length = 110
target-version = "py39"
exclude = [
    "third_party/Cutie",
    "third_party/VLPart",
    "third_party/MaskDINO",
    "third_party/masa",
    "test",
    ".eggs",
    ".git",
    ".ruff_cache",
    "__pypackages__",
    "build",
    "dist",
]


[tool.ruff.lint]
select = ["E4", "E7", "E9", "F", "I", "N", "B", "C4", "SIM"]
